### ISSUE TITLE
VSRepoGUI Shortcut Doesn't Open VSRepoGui

### ISSUE THREAD

**Issue by AlphaAtlas** [theChaosCoder/vapoursynth-portable-FATPACK#6]
Opening it gives me this error:

![Capture](https://user-images.githubusercontent.com/46462706/66928979-3c122880-f000-11e9-9588-b95aed7d9d17.JPG)

But starting VSRepoGUI.exe from the VapourSynth64 folder works fine. 

My guess is that VapourSynth64 needs to be the working directory, but... I don't know how to do that? This doesn't actually change the directory for me:
 
`%COMSPEC% /C "cd VapourSynth64 | start VSRepoGUI.exe"`

😕

**Comment by theChaosCoder** [comment]
hmm yeah something is off. It also opens the roaming scripts folder if you start it via the link.

**Comment by theChaosCoder** [comment]
I fixed the problem. Will add the new version in the next release with VS R48.
